modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All Rights Reserved"
issueTrackerURL=""

[[mods]] #mandatory
modId="primitivestart" #mandatory
version="1.19.2-1.5.0" #mandatory
displayName="Primitive Start" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/primitive-start"
logoFile="primitivestart.png" #optional
authors="ISenseHostility" #optional
description='''
    Primitive Start aims to make the start of the game a bit more interesting.
    '''

[[dependencies.primitivestart]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.primitivestart]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,)"
ordering="NONE"
side="BOTH"
